name: 🚀 Deploy

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    name: 🎉 Test and Deploy
    runs-on: ubuntu-latest 
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 🤖 Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: 🔨 Build Project
        run: |
          npm i
          npm run build

      - name: 📂 Sync files
        uses: appleboy/scp-action@master
        with: 
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASS }}
          source: "./dist/"
          target: ${{ secrets.DEPLOY_PATH }}
          strip_components: 2

